apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379  # Redis 기본 포트
      targetPort: 6379
  clusterIP: None  # StatefulSet과 함께 사용할 경우, ClusterIP를 None으로 설정
