apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport-service  # 외부 접근을 위한 NodePort 서비스
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30313  # 외부에서 접근할 포트 설정
