apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi  # Redis에 필요한 스토리지 크기 설정
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"  # 클러스터 노드의 실제 경로
