apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt의 ACME 서버
    server: https://acme-v02.api.letsencrypt.org/directory
    email: daegi0923@gmail.com  # 당신의 이메일 주소로 변경
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
