apiVersion: v1
kind: Secret
metadata:
  name: newscrab-tls
  namespace: default  # 네임스페이스 확인
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-certificate>
  tls.key: <base64-encoded-private-key>
