apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080   # Jenkins 기본 포트
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: ubuntu-home              # 호스트의 /home/ubuntu 디렉토리 마운트
          mountPath: /home/ubuntu
      - name: dind
        image: docker:19.03.12-dind   # Docker in Docker(DinD) 컨테이너
        securityContext:
          privileged: true

      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: ubuntu-home
        hostPath:
          path: /home/ubuntu              # 호스트 디렉토리 경로
          type: Directory


---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 8080
      nodePort: 30000
  type: NodePort  # 외부 접근을 위해 LoadBalancer 타입 사용
