apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport-service  # 외부 접근을 위한 NodePort 서비스
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30303  # 외부에서 접근할 포트 설정
