apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: TZ
              value: "Asia/Seoul"  # 타임존 환경 변수 설정
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"  # MySQL root 비밀번호 설정
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: config-volume
          configMap:
            name: mysql-config  # 위에서 생성한 ConfigMap 참조

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi  # 필요한 스토리지 크기 설정
