apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    log-bin=mysql-bin  # binary log 활성화
    server-id=1
    binlog-format=row
    expire_logs_days=7
    max_binlog_size=100M
    default-time-zone='+09:00'  # 타임존을 서울(UTC+9)로 설정
