apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-env-config
data:
  .env: |
    MYSQL_HOST=mysql-service
    MYSQL_PORT=3306
    MYSQL_ROOT_USER=root
    MYSQL_ROOT_PASSWORD=1234
    MYSQL_DATABASE=newscrab
