apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 3000  # React 애플리케이션이 동작할 포트
      targetPort: 3000
  type: NodePort
