apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: daegi0923/newscrab-back:latest  # Spring 애플리케이션의 Docker 이미지
          ports:
            - containerPort: 8080
