apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: daegi0923/newscrab-back:latest  # Spring 애플리케이션의 Docker 이미지
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: env-volume
              mountPath: /path/to/.env  # 컨테이너 내에서 마운트할 경로
              subPath: .env
          envFrom:
            - configMapRef:
                name: spring-env-config
      volumes:
        - name: env-volume
          configMap:
            name: spring-env-config
