spring:
    application:
        name: newscrab

    datasource:
        url: jdbc:mysql://localhost:3306/newscrab?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC # MySQL ?????? URL
        username: root # MySQL ?????? ??? ??
        password: 1234 # MySQL ?????? ????
        driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC ???? ??? ??

    jpa:
        properties:
            hibernate:
                show_sql: true # SQL ??? ??? ??
                format_sql: true # SQL ??? ?? ?? ???
        hibernate:
            ddl-auto: create # ?????? ?? ? ?????? ??? ?? ??
            database-platform: org.hibernate.dialect.MySQLDialect # MySQL Dialect ??

    #jwt:
    #secret: ${JWT_SECRET} # JWT ?? ??? ?? ?? ?
    #expiration: ${JWT_EXPIRATION} # JWT ?? ?? ?? (??? ??)

    spring.data.redis:
        host: localhost # Redis ?? ???
        port: 6379 # Redis ?? ??
        password: newscrab207 # Redis ?? ????

    server:
        port: 8080 # ?????? ?? ??

#logging:
#    level:
#        root: INFO # ?? ?? ?? ??
#        org.springframework.security: INFO # Spring Security ?? ?? ??
#        org.springframework.web: INFO # Spring Web ?? ?? ??
#        org.hibernate: INFO # Hibernate ?? ?? ??

# Swagger Configuration
#springdoc:
#    api-docs:
#    enabled: true # API ?? ?? ???
#    swagger-ui:
#    enabled: true # Swagger UI ???
#    path: /swagger-ui.html # Swagger UI ?? ?? ??

